unique_ids:
  forms: {Switch: '1621859715130702811176885.8342', Slider: VQKM7U4OEOF6Y4PUA7EDRVABBMLBEHPP,
    MessagePill: 4HMQ4AYEDJT22I2YNFTDLCQCFDA4FZ3F, Chip: JJUXHRHU5OMAZAT6Q3QT4K22KCL67Q4O,
    MultiSelectDropDown: HVA3ELK4BMIHXM33RHLUC5MR76GSTQ4G, PageBreak: WZMHYFGHS2XAT4DWAZNBJ77DOTUR2AIA,
    Tabs: REIFUFOHW7GVIYTAAVUTDZAKATHFJ5OW, Quill: ENPP7ERNGECFLY24YCU7S5PRQQHJEQ7V,
    ChipsInput: 2IUXJPHSKH5CW7WV2N2PTL2O6WAEWBPV, Demo: 7OHCYYNDEID2BZ5AN5DDP7K4XXGJTRZB,
    Autocomplete: BCY2XYD72YQ6XE35WSGDYNNDBRCSMYNV, ProgressBar.Determinate: J7HWVD2WBMZY7OCSOPNLPLHFQ4XCJBR2,
    Pivot: XGSRYGA4QFP5H57CKNWXCVOT5H7DGTEV, ProgressBar.Indeterminate: KSULDKU4IPBMWPU7OQLLU4YN35XCYTSV}
  modules: {utils._component_helpers: '1621686339258612945000771.5087', utils._writeback_waiter: HPGIMFEAETCBPEDMGJSTIJXSMGGV4LMU,
    storage: YCJGWKTKWGKIXPMF7R6FT2N5QH3TBETA, augment: DXXSTVAMYSLYZJOQS23I7R67JNE3YDEQ,
    routing._navigation: MXGZMA7IRSF5XJMMR4XOL4O2J7KNYSI4, uuid: COAWBUSWZWBIJD75BBIBE7GAILKFICZF,
    routing: 763MIXLEPUMGF6VS2I7VHTDMXSNANWA3, utils._auto_refreshing: XM2GLNNTPYT25IMV2377R4PXTQCJE2SU,
    utils._timed: M2FMBJMUW4YW7ZZXZWEVMWV5PJQPEGTV, routing._alert: YOYXSYGZW45MSIHCYVJIZUTLLK5GI7WI,
    messaging: L6OUZBWTSWZU33JG4LAY36FYKSGCO7SS, popover: B6UIKKOXGZR7QK3ZO4P32GLP5AERNF3R,
    navigation: YSGUSWEZXBEZEJKRIX7UPAS2Y64Q6EZ6, session: I6CPANLB5O7M2VDR2CZKLBV7THBW2SJF,
    ProgressBar: 6RDMGEBZGTXV32KLZDKWPGBWXS3QKNRT, routing._logging: FAODPTGNRUOWMQZKLALPJUT73LTMUDRI,
    routing._routing: SDYG54CLQVFHGY7XHB2R44TZR6PXYUKY, utils: E7XISEGXUVZXV24JEVFT4SV64AJED3XJ,
    routing._session_expired: 7I5VIVGMNIHYLE3UOMQZULQDDF6XR7UX}
  server_modules: {authorisation: Z6AZ64JBAAHAVRYQJ63VZLOU4TESTAUN, server_utils: 4XEM7IGABFRXOMKOT7WB5BYR22LF4QH7}
  assets: {loading-spinner.js: GNN5BGLOS3BHSXWTHXXQUT5BPTJQEUXA, standard-page.html: JYT2VG6NOSSLRNZR5GDSLLXUFJ7AZF4J,
    theme.css: S5NWY72JOUFUHCDRRQX7DV3C5CKF4TGN}
